name: Release

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.ADMIN_TOKEN }}

            - name: Prepare repository
              run: git fetch --unshallow --tags

            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Restore Cached node_modules
              uses: actions/cache@v3
              with:
                key: ${{ runner.os }}-node_modules
                path: node_modules

            - name: Install dependencies
              uses: bahmutov/npm-install@v1
              with:
                  install-command: yarn install

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                key: ${{ runner.os }}-node_modules
                path: node_modules

            - name: Build Addons & Demo
              run: yarn build

            - name: Cache Storybook
              uses: actions/cache@v3
              with:
                key: ${{ runner.os }}-storybook-static
                path: demo/storybook-static

            - name: Create Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn release

            - name: Create Changelog
              run: |
                  yarn changelog
                  git add .
                  git commit -a -m 'chore(release): Update `CHANGELOG.md` [skip ci]'
                  git push